### ISSUE TITLE
Smart import

### ISSUE THREAD

**Issue by AlexZd** [mojidabckuu/FluentJ#5]
In case if `keysForKeyPaths:` doesn't contain a key for certain keyPath, check object for with keyPath `respondsToSelector:`. And if it is success use keyPath as a key. In this case `keysForKeyPaths:` won't be mandatory or can contain only diff keys.

**Comment by mojidabckuu** [comment]
If `keysForKeyPaths:` returns `nil` value then dictionary of default properties will be used.
